// web/src/shared/MovieCard.tsx
import type { Component } from "solid-js";
import type { SimpleMovie } from "../types/Movie";

type MovieCardProps = {
  movie: SimpleMovie;
};

const MovieCard: Component<MovieCardProps> = props => (
  <div class='bg-primary hover:bg-secondary rounded-lg shadow-lg overflow-hidden transition-colors duration-300'>
    <a href={`/movies/details/${props.movie.ID}`}>
      <img
        src={props.movie.thumb}
        alt={props.movie.title}
        class='w-full h-64 object-cover'
        loading='lazy'
      />
    </a>

    <div class='p-4'>
      <h3 class='text-light text-xl font-bold mb-2'>{props.movie.title}</h3>

      <p class='text-blue-300'>{props.movie.year}</p>
    </div>
  </div>
);

export default MovieCard;

// tv/components/MovieCard.tsx
import { View, Text, Pressable, Image } from "react-native";
import { getTMDBImageURL, getPlaceholder } from "@/lib/imagePlaceholders";
import type { SimpleMovie } from "@/types/Movie";

type MovieCardProps = {
  movie: SimpleMovie;
  hasTVPreferredFocus?: boolean;
};

export default function MovieCard({
  movie,
  hasTVPreferredFocus = false,
}: MovieCardProps) {
  return (
    <Pressable
      className={`
        w-[200px] rounded-lg overflow-hidden bg-primary/20
        transform transition-all duration-200
        focus:scale-110 focus:bg-secondary/20
        focus:ring-2 focus:ring-secondary
      `}
      focusable={true}
      hasTVPreferredFocus={hasTVPreferredFocus}
    >
      {/* Thumbnail */}
      <View className='relative'>
        <Image source={{ uri: movie.thumb }} className='w-full aspect-[2/3]' />

        {/* Gradient Overlay */}
        <View className='absolute inset-0 bg-gradient-to-t from-dark/90 to-transparent' />
      </View>

      {/* Content */}
      <View className='p-4'>
        <Text className='text-light text-xl font-bold mb-2' numberOfLines={1}>
          {movie.title}
        </Text>
        <Text className='text-info text-lg' numberOfLines={1}>
          {movie.year}
        </Text>
      </View>
    </Pressable>
  );
}
