// web/src/shared/MovieCard.tsx
import { A } from "@solidjs/router";
import type { Component } from "solid-js";
import type { SimpleMovie } from "../types/Movie";

type MovieCardProps = {
  movie: SimpleMovie;
};

const MovieCard: Component<MovieCardProps> = props => (
  <div class='bg-primary hover:bg-secondary rounded-lg shadow-lg overflow-hidden transition-colors duration-300'>
    <A href={`/movies/details/${props.movie.ID}`}>
      <img
        src={props.movie.thumb}
        alt={props.movie.title}
        class='w-full h-64 object-cover'
        loading='lazy'
      />
    </A>

    <div class='p-4'>
      <h3 class='text-light text-xl font-bold mb-2'>{props.movie.title}</h3>

      <p class='text-blue-300'>{props.movie.year}</p>
    </div>
  </div>
);

export default MovieCard;

// web/src/shared/MovieCard.jsx
import PropTypes from "prop-types";
import { Link } from "react-router-dom";

export default function MovieCard({ movie }) {
  return (
    <div className='bg-primary hover:bg-secondary rounded-lg shadow-lg overflow-hidden transition-colors duration-300'>
      <Link to={`/movies/details/${movie.ID}`}>
        <img
          src={movie.thumb}
          alt={movie.title}
          className='w-full h-64 object-cover'
          loading='lazy'
        />
      </Link>

      <div className='p-4'>
        <h3 className='text-light text-xl font-bold mb-2'>{movie.title}</h3>

        <p className='text-blue-300'>{movie.year}</p>
      </div>
    </div>
  );
}

MovieCard.propTypes = {
  movie: PropTypes.shape({
    ID: PropTypes.number.isRequired,
    title: PropTypes.string.isRequired,
    thumb: PropTypes.string.isRequired,
    year: PropTypes.number.isRequired,
  }).isRequired,
};
