// web/src/components/Login.tsx
import { useState } from "react";
import { FiUser, FiLock } from "react-icons/fi";
import useAuth from "@/hooks/useAuth";

export default function Login() {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");
  const { setUser } = useAuth();

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsLoading(true);
    setError("");

    const formData = new FormData(e.currentTarget);
    const username = formData.get("username") as string;
    const password = formData.get("password") as string;

    try {
      const response = await fetch("/api/v1/auth/login", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ username, password }),
      });

      if (!response.ok) {
        throw new Error("Invalid credentials");
      }

      const data = await response.json();
      setUser(data.user);
    } catch (err) {
      setError(err instanceof Error ? err.message : "An error occurred");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className='min-h-screen flex items-center justify-center bg-gradient-to-br from-sky-950 via-blue-900 to-indigo-950'>
      <div className='max-w-md w-full space-y-8 p-10 bg-slate-900/50 backdrop-blur-sm rounded-xl shadow-xl'>
        <div className='text-center'>
          <h2 className='mt-6 text-3xl font-bold text-white'>Welcome back</h2>
          <p className='mt-2 text-sm text-blue-200'>Sign in to your account</p>
        </div>
        <form className='mt-8 space-y-6' onSubmit={handleSubmit}>
          <div className='rounded-md shadow-sm -space-y-px'>
            <div className='relative'>
              <FiUser className='absolute top-3 left-3 text-blue-300' />
              <input
                id='username'
                name='username'
                type='text'
                required
                className='appearance-none rounded-t-md relative block w-full px-10 py-2 border border-slate-700 bg-slate-800/50 placeholder-blue-300 text-white focus:outline-none focus:ring-blue-500 focus:border-blue-500 focus:z-10'
                placeholder='Username'
              />
            </div>
            <div className='relative'>
              <FiLock className='absolute top-3 left-3 text-blue-300' />
              <input
                id='password'
                name='password'
                type='password'
                required
                className='appearance-none rounded-b-md relative block w-full px-10 py-2 border border-slate-700 bg-slate-800/50 placeholder-blue-300 text-white focus:outline-none focus:ring-blue-500 focus:border-blue-500 focus:z-10'
                placeholder='Password'
              />
            </div>
          </div>

          {error && (
            <div className='text-red-400 text-sm text-center'>{error}</div>
          )}

          <div>
            <button
              type='submit'
              disabled={isLoading}
              className='group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed'
            >
              {isLoading ? "Signing in..." : "Sign in"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

// web/src/routes/login.tsx
import { createSignal } from "solid-js";
import { redirect, createFileRoute } from "@tanstack/solid-router";
import { FiUser, FiMail, FiLock } from "solid-icons/fi";
import ErrorWarning from "../components/ErrorWarning";
import { authState, setAuthState } from "../stores/authStore";

type SearchParams = {
  redirect?: string;
};

export const Route = createFileRoute("/login")({
  validateSearch: (search: Record<string, unknown>): SearchParams => ({
    redirect: String(search.redirect ?? "/"),
  }),
  loaderDeps: ({ search }) => search,
  beforeLoad: ({ search }) => {
    if (authState.isAuthenticated) {
      throw redirect({
        to: search.redirect,
        replace: true,
      });
    }
  },
  component: LoginPage,
});

function LoginPage() {
  const [username, setUsername] = createSignal("");
  const [email, setEmail] = createSignal("");
  const [password, setPassword] = createSignal("");
  const [error, setError] = createSignal("");
  const [isLoading, setIsLoading] = createSignal(false);
  const [isVisible, setIsVisible] = createSignal(false);

  const navigate = Route.useNavigate();
  const search = Route.useSearch();

  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    setIsLoading(true);
    setError("");
    setIsVisible(false);

    try {
      const res = await fetch("/api/v1/auth/login", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        credentials: "same-origin",
        body: JSON.stringify({
          username: username(),
          email: email(),
          password: password(),
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.error || res.statusText);
        setIsVisible(true);
        return;
      }

      setAuthState({
        user: data.user,
        isAuthenticated: true,
      });

      navigate({
        to: search().redirect,
        from: Route.fullPath,
        replace: true,
      });
    } catch (err) {
      console.error(err);
      setError("A network error occurred");
      setIsVisible(true);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div class="min-h-screen flex items-center justify-center px-4 sm:px-6 lg:px-8">
      <section class="max-w-md w-full space-y-8 bg-blue-950/50 backdrop-blur-sm p-8 rounded-xl shadow-lg shadow-blue-900/20">
        <header>
          <h1 class="text-center text-3xl font-bold text-white">
            Sign in to your account
          </h1>
        </header>

        <form
          class="mt-8 space-y-6"
          onSubmit={handleSubmit}
          aria-label="Login form"
        >
          <ErrorWarning error={error()} isVisible={isVisible()} />
          <fieldset class="space-y-4 rounded-md">
            <legend class="sr-only">Login credentials</legend>

            <div>
              <label for="username" class="sr-only">
                Username
              </label>

              <div class="relative">
                <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <FiUser class="h-5 w-5 text-yellow-300" aria-hidden="true" />
                </div>

                <input
                  autofocus
                  id="username"
                  name="username"
                  type="text"
                  required
                  class="appearance-none relative block w-full px-10 py-2 border border-blue-800/20 bg-blue-900/50 text-white rounded-md focus:outline-none focus:ring-2 focus:ring-yellow-300 focus:border-yellow-300 focus:z-10 sm:text-sm placeholder:text-blue-200/50"
                  placeholder="Username"
                  aria-required="true"
                  value={username()}
                  onInput={(e) => setUsername(e.currentTarget.value)}
                />
              </div>
            </div>

            <div>
              <label for="email" class="sr-only">
                Email
              </label>

              <div class="relative">
                <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <FiMail class="h-5 w-5 text-yellow-300" aria-hidden="true" />
                </div>

                <input
                  id="email"
                  name="email"
                  type="email"
                  required
                  class="appearance-none relative block w-full px-10 py-2 border border-blue-800/20 bg-blue-900/50 text-white rounded-md focus:outline-none focus:ring-2 focus:ring-yellow-300 focus:border-yellow-300 focus:z-10 sm:text-sm placeholder:text-blue-200/50"
                  placeholder="Email address"
                  aria-required="true"
                  value={email()}
                  onInput={(e) => setEmail(e.currentTarget.value)}
                />
              </div>
            </div>

            <div>
              <label for="password" class="sr-only">
                Password
              </label>

              <div class="relative">
                <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <FiLock class="h-5 w-5 text-yellow-300" aria-hidden="true" />
                </div>

                <input
                  id="password"
                  name="password"
                  type="password"
                  required
                  class="appearance-none relative block w-full px-10 py-2 border border-blue-800/20 bg-blue-900/50 text-white rounded-md focus:outline-none focus:ring-2 focus:ring-yellow-300 focus:border-yellow-300 focus:z-10 sm:text-sm placeholder:text-blue-200/50"
                  placeholder="Password"
                  aria-required="true"
                  value={password()}
                  onInput={(e) => setPassword(e.currentTarget.value)}
                />
              </div>
            </div>
          </fieldset>

          <div>
            <button
              type="submit"
              disabled={isLoading()}
              class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-yellow-300 disabled:opacity-50 disabled:cursor-not-allowed transition-colors duration-200"
              aria-busy={isLoading()}
            >
              {isLoading() ? "Signing in..." : "Sign in"}
            </button>
          </div>
        </form>
      </section>
    </div>
  );
}
