// web/src/components/Login.tsx
import { useState } from "react";
import { FiUser, FiLock } from "react-icons/fi";
import useAuth from "@/hooks/useAuth";

export default function Login() {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState("");
  const { setUser } = useAuth();

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsLoading(true);
    setError("");

    const formData = new FormData(e.currentTarget);
    const username = formData.get("username") as string;
    const password = formData.get("password") as string;

    try {
      const response = await fetch("/api/v1/auth/login", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ username, password }),
      });

      if (!response.ok) {
        throw new Error("Invalid credentials");
      }

      const data = await response.json();
      setUser(data.user);
    } catch (err) {
      setError(err instanceof Error ? err.message : "An error occurred");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className='min-h-screen flex items-center justify-center bg-gradient-to-br from-sky-950 via-blue-900 to-indigo-950'>
      <div className='max-w-md w-full space-y-8 p-10 bg-slate-900/50 backdrop-blur-sm rounded-xl shadow-xl'>
        <div className='text-center'>
          <h2 className='mt-6 text-3xl font-bold text-white'>Welcome back</h2>
          <p className='mt-2 text-sm text-blue-200'>Sign in to your account</p>
        </div>
        <form className='mt-8 space-y-6' onSubmit={handleSubmit}>
          <div className='rounded-md shadow-sm -space-y-px'>
            <div className='relative'>
              <FiUser className='absolute top-3 left-3 text-blue-300' />
              <input
                id='username'
                name='username'
                type='text'
                required
                className='appearance-none rounded-t-md relative block w-full px-10 py-2 border border-slate-700 bg-slate-800/50 placeholder-blue-300 text-white focus:outline-none focus:ring-blue-500 focus:border-blue-500 focus:z-10'
                placeholder='Username'
              />
            </div>
            <div className='relative'>
              <FiLock className='absolute top-3 left-3 text-blue-300' />
              <input
                id='password'
                name='password'
                type='password'
                required
                className='appearance-none rounded-b-md relative block w-full px-10 py-2 border border-slate-700 bg-slate-800/50 placeholder-blue-300 text-white focus:outline-none focus:ring-blue-500 focus:border-blue-500 focus:z-10'
                placeholder='Password'
              />
            </div>
          </div>

          {error && (
            <div className='text-red-400 text-sm text-center'>{error}</div>
          )}

          <div>
            <button
              type='submit'
              disabled={isLoading}
              className='group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed'
            >
              {isLoading ? "Signing in..." : "Sign in"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

// web/src/routes/login/+page.svelte
<script>
  import { FontAwesomeIcon } from '@fortawesome/svelte-fontawesome';
  import { faEnvelope, faLock } from '@fortawesome/free-solid-svg-icons';
</script>

<!-- full-page wrapper -->
<div class="min-h-dvh flex flex-col items-center justify-center bg-gradient-to-b from-slate-900 via-blue-950/80 to-slate-900 px-4">
  <!-- Card -->
  <div class="w-full max-w-md rounded-2xl border border-slate-800 bg-slate-900/70 backdrop-blur p-8 shadow-xl">
    <!-- Header -->
    <div class="text-center mb-8">
      <h1 class="text-3xl font-bold text-sky-400">Welcome to Igloo</h1>
      <p class="mt-2 text-slate-400">Log in to your account to access your media library.</p>
    </div>

    <form class="space-y-6">
      <div>
        <label for="email" class="block text-sm font-medium text-slate-300 mb-1">Email</label>
        <div class="relative">
          <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-slate-400">
            <FontAwesomeIcon icon={faEnvelope} class="w-5 h-5" />
          </span>
          <input
          autofocus
          type="email"
            id="email"
            name="email"
            required
            placeholder="you@example.com"
            class="w-full rounded-xl bg-slate-800/70 border border-slate-700 text-slate-100 placeholder-slate-500
                   pl-10 pr-3 py-2 focus:outline-none focus:ring-2 focus:ring-yellow-400 focus:border-yellow-400"
          />
        </div>
      </div>

      <div>
        <label for="password" class="block text-sm font-medium text-slate-300 mb-1">Password</label>
        <div class="relative">
          <span class="absolute inset-y-0 left-0 flex items-center pl-3 text-slate-400">
            <FontAwesomeIcon icon={faLock} class="w-5 h-5" />
          </span>
          <input
            id="password"
            type="password"
            bind:value={password}
            minlength="8"
            required
            placeholder="••••••••"
            class="w-full rounded-xl bg-slate-800/70 border border-slate-700 text-slate-100 placeholder-slate-500
                   pl-10 pr-3 py-2 focus:outline-none focus:ring-2 focus:ring-yellow-400 focus:border-yellow-400"
          />
        </div>
      </div>

      <!-- Submit -->
      <div class="pt-2">
        <button
          type="submit"
          class="w-full rounded-xl bg-yellow-400 hover:bg-yellow-300 text-slate-900 font-semibold py-2
                 transition focus:outline-none focus:ring-2 focus:ring-yellow-400"
        >
          Log In
        </button>
      </div>
    </form>

    <!-- Footer -->
    <p class="mt-6 text-center text-sm text-slate-500">
      Don’t have an account yet?
      <a href="/register" class="text-sky-400 hover:text-yellow-400 font-medium focus:outline-none focus:ring-2 focus:ring-yellow-400 rounded">
        Sign up
      </a>
    </p>
  </div>
</div>
