// web/src/shared/Navbar.jsx
import { useState } from "react";
import { NavLink, Link } from "react-router-dom";
import logo from "../assets/images/igloo-icon.png";
import profileDefault from "../assets/images/profile.png";
import { FaUser } from "react-icons/fa";

export default function Navbar() {
  const user = null;

  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [isProfileMenuOpen, setIsProfileMenuOpen] = useState(false);

  return (
    <nav className='bg-blue-700 border-b border-blue-500'>
      <div className='mx-auto max-w-7xl px-2 sm:px-6 lg:px-8'>
        <div className='relative flex h-20 items-center justify-between'>
          <div className='absolute inset-y-0 left-0 flex items-center md:hidden'>
            {/* <!-- Mobile menu button--> */}
            <button
              type='button'
              id='mobile-dropdown-button'
              className='relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white'
              aria-controls='mobile-menu'
              aria-expanded={isMobileMenuOpen}
              onClick={() => setIsMobileMenuOpen(prev => !prev)}
            >
              <span className='absolute -inset-0.5'></span>
              <span className='sr-only'>Open main menu</span>
              <svg
                className='block h-6 w-6'
                fill='none'
                viewBox='0 0 24 24'
                strokeWidth='1.5'
                stroke='currentColor'
                aria-hidden='true'
              >
                <path
                  strokeLinecap='round'
                  strokeLinejoin='round'
                  d='M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5'
                />
              </svg>
            </button>
          </div>

          <div className='flex flex-1 items-center justify-center md:items-stretch md:justify-start'>
            {/* <!-- Logo --> */}
            <Link className='flex flex-shrink-0 items-center' to='/'>
              <img className='h-10 w-auto' src={logo} alt='Igloo logo' />

              <span className='hidden md:block text-white text-2xl font-bold ml-2'>
                Igloo
              </span>
            </Link>

            {/* <!-- Desktop Menu Hidden below md screens --> */}
            <div className='hidden md:ml-6 md:block'>
              <div className='flex space-x-2'>
                <NavLink
                  to='/'
                  className='text-white hover:bg-gray-900 hover:text-white rounded-md px-3 py-2'
                >
                  Home
                </NavLink>

                <NavLink
                  to='/movies/1'
                  className='text-white hover:bg-gray-900 hover:text-white rounded-md px-3 py-2'
                >
                  Movies
                </NavLink>

                <NavLink
                  to='/tv-shows'
                  className='text-white hover:bg-gray-900 hover:text-white rounded-md px-3 py-2'
                >
                  TV Shows
                </NavLink>

                <NavLink
                  to='/music'
                  className='text-white hover:bg-gray-900 hover:text-white rounded-md px-3 py-2'
                >
                  Music
                </NavLink>

                <NavLink
                  to='/photos'
                  className='text-white hover:bg-gray-900 hover:text-white rounded-md px-3 py-2'
                >
                  Photos
                </NavLink>
              </div>
            </div>
          </div>

          {/* <!-- Right Side Menu (Logged Out) --> */}
          {!user && (
            <div className='hidden md:block md:ml-6'>
              <div className='flex items-center'>
                <Link
                  to='/login'
                  className='flex items-center text-white bg-gray-700 hover:bg-gray-900 hover:text-white rounded-md px-3 py-2'
                >
                  <FaUser className='text-white mr-2' />
                  <span>Login or Register</span>
                </Link>
              </div>
            </div>
          )}

          {/* <!-- Right Side Menu (Logged In) --> */}
          {user && (
            <div className='absolute inset-y-0 right-0 flex items-center pr-2 md:static md:inset-auto md:ml-6 md:pr-0'>
              {/* <!-- Profile dropdown button --> */}
              <div className='relative ml-3'>
                <div>
                  <button
                    type='button'
                    className='relative flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800'
                    id='user-menu-button'
                    aria-expanded={isProfileMenuOpen}
                    aria-haspopup='true'
                    onClick={() => setIsProfileMenuOpen(prev => !prev)}
                  >
                    <span className='absolute -inset-1.5'></span>
                    <span className='sr-only'>Open user menu</span>
                    <img
                      className='h-8 w-8 rounded-full'
                      src={profileDefault}
                      alt=''
                      width={40}
                      height={40}
                    />
                  </button>
                </div>

                {/* <!-- Profile dropdown --> */}
                {isProfileMenuOpen && (
                  <div
                    id='user-menu'
                    className='absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none'
                    role='menu'
                    aria-orientation='vertical'
                    aria-labelledby='user-menu-button'
                    tabIndex={-1}
                  >
                    <NavLink
                      to='/settings'
                      className='block px-4 py-2 text-sm text-gray-700'
                      role='menuitem'
                      tabIndex={-1}
                      id='user-menu-item-0'
                      onClick={() => {
                        setIsProfileMenuOpen(false);
                      }}
                    >
                      Settings
                    </NavLink>

                    <NavLink
                      to='/profile'
                      className='block px-4 py-2 text-sm text-gray-700'
                      role='menuitem'
                      tabIndex={-1}
                      id='user-menu-item-2'
                      onClick={() => {
                        setIsProfileMenuOpen(false);
                      }}
                    >
                      Profile
                    </NavLink>

                    <button
                      onClick={() => {
                        setIsProfileMenuOpen(false);
                        console.log("sign out");
                      }}
                      className='block px-4 py-2 text-sm text-gray-700'
                      role='menuitem'
                      tabIndex={-1}
                      id='user-menu-item-2'
                    >
                      Sign Out
                    </button>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* <!-- Mobile menu, show/hide based on menu state. --> */}
      {isMobileMenuOpen && (
        <div id='mobile-menu'>
          <div className='space-y-1 px-2 pb-3 pt-2'>
            <NavLink
              to='/'
              className='text-white block rounded-md px-3 py-2 text-base font-medium'
            >
              Home
            </NavLink>

            <NavLink
              to='/movies/1'
              className='text-white block rounded-md px-3 py-2 text-base font-medium'
            >
              Movies
            </NavLink>

            <NavLink
              to='/tv-shows'
              className='text-white block rounded-md px-3 py-2 text-base font-medium'
            >
              TV Shows
            </NavLink>

            <NavLink
              to='/music'
              className='text-white block rounded-md px-3 py-2 text-base font-medium'
            >
              Music
            </NavLink>

            <NavLink
              to='/photos'
              className='text-white block rounded-md px-3 py-2 text-base font-medium'
            >
              Photos
            </NavLink>

            {!user && (
              <button className='flex items-center text-white bg-gray-700 hover:bg-gray-900 hover:text-white rounded-md px-3 py-2'>
                <span>Login or Register</span>
              </button>
            )}
          </div>
        </div>
      )}
    </nav>
  );
}

// web/src/components/Navbar.tsx
import { createSignal, onCleanup, onMount, Show } from "solid-js";
import { Link } from "@tanstack/solid-router";
import {
  FiHome,
  FiFilm,
  FiTv,
  FiMusic,
  FiMenu,
  FiX,
  FiSettings,
  FiLogOut,
  FiLogIn,
} from "solid-icons/fi";
import iglooLogo from "../assets/images/logo-alt.png";
import { authState, setAuthState } from "../stores/authStore";

export default function Navbar() {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = createSignal(false);
  let mobileMenuRef: HTMLDivElement | undefined;
  let menuButtonRef: HTMLButtonElement | undefined;
  const { isAuthenticated } = authState;

  onMount(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (
        isMobileMenuOpen() &&
        mobileMenuRef &&
        !mobileMenuRef.contains(event.target as Node) &&
        menuButtonRef &&
        !menuButtonRef.contains(event.target as Node)
      ) {
        setIsMobileMenuOpen(false);
      }
    };

    document.addEventListener("mousedown", handleClickOutside);

    onCleanup(() => {
      document.removeEventListener("mousedown", handleClickOutside);
    });
  });

  const toggleMobileMenu = () => setIsMobileMenuOpen(!isMobileMenuOpen());

  const handleSignOut = async () => {
    setAuthState({
      user: null,
      isAuthenticated: false,
      isLoading: false,
    });
  };

  return (
    <>
      {/* Fade Overlay */}
      <div
        class={`fixed inset-0 bg-gradient-to-b from-slate-950/80 to-blue-950/80 backdrop-blur-sm transition-all duration-300 md:hidden ${
          isMobileMenuOpen() ? "opacity-100" : "opacity-0 pointer-events-none"
        }`}
        onClick={() => setIsMobileMenuOpen(false)}
        aria-hidden="true"
      />

      <nav class="fixed top-0 left-0 right-0 bg-slate-900/95 shadow-lg shadow-blue-900/20 backdrop-blur-sm z-50">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div class="flex items-center justify-between h-16">
            {/* Left side - Logo and Navigation */}
            <div class="flex items-center gap-8">
              <Link
                to="/"
                class="flex items-center gap-2 text-white hover:text-blue-300 transition-colors"
                preload="intent"
              >
                <img src={iglooLogo} alt="Igloo" class="h-8 w-auto" />
                <span class="text-xl font-semibold bg-gradient-to-r from-blue-200 to-blue-100 text-transparent bg-clip-text">
                  Igloo
                </span>
              </Link>

              {/* Desktop Navigation Links */}
              <div class="hidden md:flex items-center gap-1">
                {/* Home link - always visible */}
                <Link
                  to="/"
                  preload="intent"
                  class="px-3 py-2 rounded-md text-sm font-medium text-blue-200 hover:text-white hover:bg-blue-500/10 transition-opacity duration-300 ease-in-out flex items-center gap-2 relative group"
                >
                  <FiHome class="w-4 h-4" aria-hidden={true} />
                  Home
                  <span class="absolute inset-x-0 -bottom-px h-px bg-gradient-to-r from-transparent via-blue-500 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                </Link>

                {/* Authenticated Navigation Links */}
                <Show when={isAuthenticated}>
                  <Link
                    to="/movies"
                    preload="intent"
                    class="px-3 py-2 rounded-md text-sm font-medium text-blue-200 hover:text-white hover:bg-blue-500/10 transition-opacity duration-300 ease-in-out flex items-center gap-2 relative group"
                  >
                    <FiFilm class="w-4 h-4" aria-hidden={true} />
                    Movies
                    <span class="absolute inset-x-0 -bottom-px h-px bg-gradient-to-r from-transparent via-blue-500 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                  </Link>

                  <Link
                    to="/tvshows"
                    preload="intent"
                    class="px-3 py-2 rounded-md text-sm font-medium text-blue-200 hover:text-white hover:bg-blue-500/10 transition-opacity duration-300 ease-in-out flex items-center gap-2 relative group"
                  >
                    <FiTv class="w-4 h-4" aria-hidden={true} />
                    TV Shows
                    <span class="absolute inset-x-0 -bottom-px h-px bg-gradient-to-r from-transparent via-blue-500 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                  </Link>

                  <Link
                    to="/music"
                    preload="intent"
                    class="px-3 py-2 rounded-md text-sm font-medium text-blue-200 hover:text-white hover:bg-blue-500/10 transition-opacity duration-300 ease-in-out flex items-center gap-2 relative group"
                  >
                    <FiMusic class="w-4 h-4" aria-hidden={true} />
                    Music
                    <span class="absolute inset-x-0 -bottom-px h-px bg-gradient-to-r from-transparent via-blue-500 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                  </Link>
                </Show>
              </div>
            </div>

            {/* Right side - Settings, Sign In/Out, and Mobile Menu Button */}
            <div class="flex items-center gap-2">
              <Show
                when={isAuthenticated}
                fallback={
                  <Link
                    to="/login"
                    class="text-blue-200 hover:text-white px-3 py-2 rounded-md text-sm font-medium hover:bg-blue-500/10 transition-opacity duration-300 ease-in-out flex items-center gap-2"
                  >
                    <FiLogIn aria-hidden={true} /> Sign In
                  </Link>
                }
              >
                <>
                  {/* Settings Link */}
                  <Link
                    to="/"
                    class="text-blue-200 hover:text-white px-3 py-2 rounded-md text-sm font-medium hover:bg-blue-500/10 transition-opacity duration-300 ease-in-out flex items-center gap-2"
                  >
                    <FiSettings aria-hidden={true} /> Settings
                  </Link>

                  {/* Sign Out Button */}
                  <button
                    onClick={handleSignOut}
                    class="text-blue-200 hover:text-white px-3 py-2 rounded-md text-sm font-medium hover:bg-blue-500/10 transition-opacity duration-300 ease-in-out flex items-center gap-2"
                  >
                    <FiLogOut aria-hidden={true} /> Sign Out
                  </button>

                  {/* Mobile Menu Button */}
                  <button
                    ref={menuButtonRef}
                    type="button"
                    class="md:hidden p-2 rounded-md text-blue-200 hover:text-white hover:bg-blue-500/10 transition-opacity duration-300 ease-in-out"
                    onClick={toggleMobileMenu}
                    aria-expanded={isMobileMenuOpen()}
                    aria-label="Toggle mobile menu"
                  >
                    <Show
                      when={isMobileMenuOpen()}
                      fallback={<FiMenu class="w-6 h-6" aria-hidden={true} />}
                    >
                      <FiX class="w-6 h-6" aria-hidden={true} />
                    </Show>
                  </button>
                </>
              </Show>
            </div>
          </div>
        </div>

        {/* Mobile Navigation Menu */}
        <Show when={isAuthenticated}>
          <div
            ref={mobileMenuRef}
            class={`md:hidden transition-all duration-300 ease-in-out ${
              isMobileMenuOpen()
                ? "max-h-96 opacity-100"
                : "max-h-0 opacity-0 pointer-events-none"
            }`}
          >
            <div class="px-2 pt-2 pb-3 space-y-1 bg-slate-900/95 backdrop-blur-sm border-t border-blue-900/20">
              <Link
                to="/"
                preload="intent"
                class="px-3 py-2 rounded-md text-base font-medium text-blue-200 hover:text-white hover:bg-blue-500/10 transition-colors flex items-center gap-3"
                onClick={() => setIsMobileMenuOpen(false)}
              >
                <FiHome class="w-5 h-5" aria-hidden={true} />
                Home
              </Link>

              <Link
                to="/movies"
                preload="intent"
                class="px-3 py-2 rounded-md text-base font-medium text-blue-200 hover:text-white hover:bg-blue-500/10 transition-colors flex items-center gap-3"
                onClick={() => setIsMobileMenuOpen(false)}
              >
                <FiFilm class="w-5 h-5" aria-hidden={true} />
                Movies
              </Link>

              <Link
                to="/tvshows"
                preload="intent"
                class="px-3 py-2 rounded-md text-base font-medium text-blue-200 hover:text-white hover:bg-blue-500/10 transition-colors flex items-center gap-3"
                onClick={() => setIsMobileMenuOpen(false)}
              >
                <FiTv class="w-5 h-5" aria-hidden={true} />
                TV Shows
              </Link>

              <Link
                to="/music"
                preload="intent"
                class="px-3 py-2 rounded-md text-base font-medium text-blue-200 hover:text-white hover:bg-blue-500/10 transition-colors flex items-center gap-3"
                onClick={() => setIsMobileMenuOpen(false)}
              >
                <FiMusic class="w-5 h-5" aria-hidden={true} />
                Music
              </Link>
            </div>
          </div>
        </Show>
      </nav>
    </>
  );
}
