// web/src/shared/MovieCard.tsx
import type { Component } from "solid-js";
import type { SimpleMovie } from "../types/Movie";

type MovieCardProps = {
  movie: SimpleMovie;
};

const MovieCard: Component<MovieCardProps> = props => (
  <div class='bg-primary hover:bg-secondary rounded-lg shadow-lg overflow-hidden transition-colors duration-300'>
    <a href={`/movies/details/${props.movie.ID}`}>
      <img
        src={props.movie.thumb}
        alt={props.movie.title}
        class='w-full h-64 object-cover'
        loading='lazy'
      />
    </a>

    <div class='p-4'>
      <h3 class='text-light text-xl font-bold mb-2'>{props.movie.title}</h3>

      <p class='text-blue-300'>{props.movie.year}</p>
    </div>
  </div>
);

export default MovieCard;

// web/src/lib/components/MovieCard.svelte
<script>
  export let id;
  export let title;
  export let thumb;
  export let year;
</script>

<div class="max-w-sm mx-auto bg-primary hover:bg-secondary shadow-md rounded-lg overflow-hidden">
  <a href={`/movies/${id}`}>
    <img src={thumb} alt={title} class="w-full object-cover" />
  </a>

  <div class="p-5 text-xl text-center">
    <h5 class="mb-2 font-bold">{title}</h5>
    <p class="mb-2">{year}</p>
  </div>
</div>
